apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  namespace: {{ .Release.Namespace }} 
  labels :
    app : {{.Values.appname}}
spec:
  selector: 
    matchLabels:
      app: {{.Values.appname}}
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.appname}}
    spec:
      containers:
      - image:  {{.Values.image.juiceimage}}
        name: {{.Values.appname}}
        ports:
        - containerPort: 3000
          name: {{.Values.appname}}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: juice-service
  labels:
    app: {{.Values.appname}}
spec: 
  ports:
   - port: 80
     targetPort: 3000
  selector:
    app: {{.Values.appname}}
  type: ClusterIP
  
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-configuration
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    
spec:
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.location }}.{{ .Values.urlsuffix }} 
    http:
      paths:
      - path: /
        backend:
          serviceName: juice-service
          servicePort: 80
