name: Build
on:
  push:
    branches:
    - main
    paths:
    - '_build_flag'
jobs:
  build: 
     runs-on: ubuntu-latest
     env:
      working-directory: .
      WAAP_TOKEN: ${{ secrets.WAAP_TOKEN }}
      CSPM_API: ${{ secrets.CSPM_API }}
      CSPM_SECRET: ${{ secrets.CSPM_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZ_RG: ${{ secrets.AZ_RG }}
      AZ_LOCATION: ${{ secrets.AZ_LOCATION }}
      URL_SUFFIX: ${{ secrets.URL_SUFFIX }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      K8_CSPM_NAME: ${{ secrets.K8_CSPM_NAME }}
      NAMESPACE: ${{ secrets.NAMESPACE }}
      ORG_NAME: "WAAP_JUICE_K8"
     
     steps: 
 #Checkout code from repository
     - name: Checkout Code
       uses: actions/checkout@v1 
 #Create Azure Resource Group,and build AKS Cluster
     - name: Configure Azure Environment
       run: |
         location_lower=$(echo "${AZ_LOCATION}" | awk '{print tolower($0)}')
         location_lower="$(echo -e "$location_lower" | tr -d '[:space:]')"
         az login  --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} -t ${AZURE_TENANT_ID}
         az group create -n ${AZ_RG} -l ${location_lower}
         az aks create --name ${CLUSTER_NAME} --resource-group ${AZ_RG} --node-count 3 --generate-ssh-keys --service-principal $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET
       timeout-minutes: 30  

#Install Helm
     - uses: azure/setup-helm@v1
       id: install       

#Package and Install Helm Chart for Juice SHop + WAAP
     - name: Deploy Helm Chart of APP
       run: |
          location_lower=$(echo "${AZ_LOCATION}" | awk '{print tolower($0)}')
          location_lower="$(echo -e "$location_lower" | tr -d '[:space:]')"
          az aks get-credentials --name ${CLUSTER_NAME} --resource-group ${AZ_RG}
          helm package cloudguard_demo_chart/
          helm install juicewaap /home/runner/work/Kubernetes_Cloudguard/Kubernetes_Cloudguard/cloudguard_demo_chart-0.1.0.tgz --set token=${WAAP_TOKEN} --set appname=${NAMESPACE} --set urlsuffix=${URL_SUFFIX} --set location=${location_lower} --create-namespace --namespace ${NAMESPACE}

# DESIGNED FOR CHECK POINT SEs
     - name: Add Kubernetes cluster to Cloudguard CSPM
       run: |
        parent_org_id=$(curl -X GET https://api.dome9.com/v2/organizationalunit/view --basic -u ${CSPM_API}:${CSPM_SECRET} -H 'Accept: application/json' | jq '.| select(.name=="Check Point") | .id')
        org_id=$(curl -X POST https://api.dome9.com/v2/OrganizationalUnit --basic -u ${CSPM_API}:${CSPM_SECRET} -H 'Content-Type: application/json' --data  "{\"name\" : \"${ORG_NAME}\", "parentId" : ${parent_org_id}}" |jq '.item.id')
        k8_id=$(curl -X POST https://api.dome9.com/v2/KubernetesAccount  --basic -u ${CSPM_API}:${CSPM_SECRET} -H  'Content-Type: application/json' -H 'Accept: application/json' --data  "{\"name\" : \"${K8_CSPM_NAME}\", "organizationalUnitId" : ${org_id}}" | jq -r '.id')
        helm repo add checkpoint-ea https://raw.githubusercontent.com/CheckPointSW/charts/ea/repository/
        helm install asset-mgmt checkpoint-ea/cp-resource-management --set-string credentials.user=${CSPM_API} --set-string credentials.secret=${CSPM_SECRET} --set-string clusterID=${k8_id} --set addons.imageUploader.enabled=true --set addons.flowLogs.enabled=true   --namespace ${NAMESPACE} --create-namespace
        curl -X POST 'https://api.dome9.com/v2/KubernetesAccount/vulnerabilityAssessment/enable' --user ${CSPM_API}:${CSPM_SECRET} --header 'Content-Type: application/json' --data "{ \"cloudAccountId\": ${k8_id},   \"enabled\": true }"
        curl -X POST 'https://api.dome9.com/v2/KubernetesAccount/magellan-kubernetes-flowlogs/enable' --user ${CSPM_API}:${CSPM_SECRET} --header 'Content-Type: application/json' --data "{  \"k8sAccountId\": ${k8_id},   \"enabled\": true }"

        
        

        
    

