name: Build
on:
  push:
    branches:
    - main
    paths:
    - '_build_flag'
jobs:
  build: 
     runs-on: ubuntu-latest
     env:
      working-directory: .
      WAAP_TOKEN: ${{ secrets.CG_TOKEN }}
      CSPM_TOKEN: ${{ secrets.CSPMkub_TOKEN }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZ_RG: ${{ secrets.AZ_RG }}
      AZ_LOCATION: ${{ secrets.AZ_LOCATION }}
      URL_SUFFIX: ${{ secrets.URL_SUFFIX }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      K8_CSPM_NAME: ${{ secrets.K8_CSPM_NAME }}
      NAMESPACE: ${{ secrets.NAMESPACE }}
     
     steps: 
 #Checkout code from repository
     - name: Checkout Code
       uses: actions/checkout@v1 
 #Create Azure Resource Group,and build AKS Cluster
     - name: Configure Azure Environment
       run: |
         location_lower=$(echo "${AZ_LOCATION}" | awk '{print tolower($0)}')
         location_lower="$(echo -e "$location_lower" | tr -d '[:space:]')"
         az login  --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} -t ${AZURE_TENANT_ID}
         az group create -n ${AZ_RG} -l ${location_lower}
         az aks create --name ${CLUSTER_NAME} --resource-group  ${AZ_RG} -p ${DNS_PREFIX} --node-count 3
       timeout-minutes: 30  

#Install Helm
     - uses: azure/setup-helm@v1
       id: install       

#Package and Install Helm Chart for Juice SHop + WAAP
     - name: Deploy Helm Chart of APP
       run: |
          az aks get-credentials --name ${CLUSTER_NAME} --resource-group ${AZ_RG}
          helm package /cloudguard_demo_chart
          helm install juicewaap cloudguard_demo_chart-0.1.0.tgz --set token=${WAAP_TOKEN} --set appname=${NAMESPACE} --set urlsuffix=${URL_SUFFIX} --set location=${location_lower} --create-namespace --namespace ${NAMESPACE}

#THIS WILL ONLY WORK IF YOU HAVE A SINGLE AZURE TENANT IN DOME9
     - name: Add Kubernetes cluster to Cloudguard CSPM
       run: |
        org_id=$(curl -X GET https://api.dome9.com/v2/organizationalunit/view --basic -u  ${CHKP_CLOUDGUARD_ID}:${CHKP_CLOUDGUARD_SECRET} -H 'Accept: application/json' | jq .children[0] | jq .id)
        k8_json=$(curl -X POST https://api.dome9.com/v2/KubernetesAccount  --basic -u {CHKP_CLOUDGUARD_ID}:${CHKP_CLOUDGUARD_SECRET} -H  'Content-Type: application/json' -H 'Accept: application/json' --data  "{\"name\" : \"${K8_CSPM_NAME}\", "organizationalUnitId" : ${org_id}}")
    

