name: Destroy
on:
  push:
    branches:
    - main
    paths:
    - '_destroy_flag'
jobs:
  destroy: 
     runs-on: ubuntu-latest
     env:
      working-directory: .
      WAAP_TOKEN: ${{ secrets.CG_TOKEN }}
      CSPM_TOKEN: ${{ secrets.CSPM_TOKEN }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZ_RG: ${{ secrets.AZ_RG }}
      AZ_LOCATION: ${{ secrets.AZ_LOCATION }}
      URL_SUFFIX: ${{ secrets.URL_SUFFIX }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      K8_CSPM_NAME: ${{ secrets.K8_CSPM_NAME }}
      NAMESPACE: ${{ secrets.NAMESPACE }}
     
     steps: 
 #Checkout code from repository
     - name: Checkout Code
       uses: actions/checkout@v1 
 #Delete Azure Resource Group,and build AKS Cluster
     - name: Cleanup Azure Environment
       run: |
         location_lower=$(echo "${AZ_LOCATION}" | awk '{print tolower($0)}')
         location_lower="$(echo -e "$location_lower" | tr -d '[:space:]')"
         az login  --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} -t ${AZURE_TENANT_ID}
         az aks delete --name ${CLUSTER_NAME} --resource-group ${AZ_RG} -y
         az group delete -n ${AZ_RG} -y
       timeout-minutes: 30 
       continue-on-error: true
 #Delete Azure Resource Group,and build AKS Cluster
 
# DO NOT USE IF YOU ALREADY HAVE A KUBERNETES CLUSTER
     - name: Remove Kubernetes cluster to Cloudguard CSPM
       run: |
        org_id=$(curl -X GET https://api.dome9.com/v2/organizationalunit/view --basic -u ${CSPM_TOKEN} -H 'Accept: application/json' | jq .children[0] | jq .id)
        k8_id=$(curl -X GET https://api.dome9.com/v2/organizationalunit/cloudaccounts?id=${org_id} --basic -u ${CSPM_TOKEN}  -H 'Accept: application/json' | jq .[] | jq .kubernetes[])
        curl -X DELETE https://api.dome9.com/v2/KubernetesAccount/$k8_id --basic -u ${CSPM_TOKEN}